### ISSUE TITLE
Flutter Test UnimplementedError on Timer.tick

### ISSUE THREAD

**Issue by blackmenthor** [google/quiver-dart#481] opened 2018-10-08 06:41 UTC
Hi,

I see at this line, it says that Dart 2.0 requires to override the timer.tick method

https://github.com/google/quiver-dart/blob/54f6693e842c607ec4c9346c5003b4ce8f9e6c4d/lib/testing/src/async/fake_async.dart#L293

So how exactly to do this? does i need to supply a MockTimer as such? Or i need to implement my own Timer class?

Thanks.

**Comment by cbracken** [comment] 2019-11-05 02:42
This is a method that was added in Dart 2.0 that we haven't got around to implementing yet. The tracking bug for most of these is here:
https://github.com/google/quiver-dart/issues/418

I've updated the title of that bug to more accurately reflect that this isn't restricted just to collections. I'll close this issue as a duplicate of that.

**Closed by cbracken** 2019-11-05 02:42 UTC
Labels: question
