### ISSUE TITLE
Multimaps should be instantiable from maps and multimaps.

### ISSUE THREAD

**Issue by davidmorgan** [google/quiver-dart#251] opened 2015-05-14 10:44 UTC
e.g.

final multimap1 = new ListMultimap<int, String>({1: ['1', 'one']});
final multimap2 = new ListMultimap<int, String>(map1);

**Comment by cbracken** [comment] 2017-10-14 01:56
Closing as working as intended unless we can find strong evidence that the benefits outweigh the drawbacks.

From a conceptual point of view a multimap and a map of key to list aren't the same thing. It's certainly the underlying implementation we use but there are several significant differences. A big one is that multimaps have no concept of mapping to null. A mapping of _key_ to {} is equivalent to the absence of any mapping for _key_.

There are a lot of downsides to adding a `fromMap` constructor due to all the validation or edge-case handling we'd need to do. It would also be inconsistent with the rest of the API -- even `asMap`, since changes to the returned map are reflected in the multimap, and there's no way we could do that with the incoming map in the constructor. The main reason for the existence of `asMap` at all is simply the quantity of libraries out there that understand the core `Map` class. I suspect there are far fewer cases where someone has a Map-based multimap-like structure that they want to turn into a real multimap, with the possible exception of serialisation, maybe.

**Closed by cbracken** 2017-10-14 01:56 UTC
Labels: enhancement, wontfix
